// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.troila.cloud.microservice.user.dto;

public interface LoadUserRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LoadUserRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 1;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();
}
