// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.troila.cloud.microservice.user.dto;

public interface LoadUserReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LoadUserReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>int64 authId = 2;</code>
   */
  long getAuthId();

  /**
   * <code>string name = 3;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 3;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string password = 4;</code>
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 4;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <code>string nick = 5;</code>
   */
  java.lang.String getNick();
  /**
   * <code>string nick = 5;</code>
   */
  com.google.protobuf.ByteString
      getNickBytes();

  /**
   * <code>string telephone = 6;</code>
   */
  java.lang.String getTelephone();
  /**
   * <code>string telephone = 6;</code>
   */
  com.google.protobuf.ByteString
      getTelephoneBytes();

  /**
   * <code>string email = 7;</code>
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 7;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>string userCode = 8;</code>
   */
  java.lang.String getUserCode();
  /**
   * <code>string userCode = 8;</code>
   */
  com.google.protobuf.ByteString
      getUserCodeBytes();

  /**
   * <code>bool disable = 9;</code>
   */
  boolean getDisable();
}
