// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.troila.cloud.microservice.user.dto;

public final class UserProto {
  private UserProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LoadUserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LoadUserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LoadUserReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LoadUserReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nuser.proto\"#\n\017LoadUserRequest\022\020\n\010usern" +
      "ame\030\001 \001(\t\"\236\001\n\rLoadUserReply\022\n\n\002id\030\001 \001(\005\022" +
      "\016\n\006authId\030\002 \001(\003\022\014\n\004name\030\003 \001(\t\022\020\n\010passwor" +
      "d\030\004 \001(\t\022\014\n\004nick\030\005 \001(\t\022\021\n\ttelephone\030\006 \001(\t" +
      "\022\r\n\005email\030\007 \001(\t\022\020\n\010userCode\030\010 \001(\t\022\017\n\007dis" +
      "able\030\t \001(\010B5\n&com.troila.cloud.microserv" +
      "ice.user.dtoB\tUserProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_LoadUserRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_LoadUserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LoadUserRequest_descriptor,
        new java.lang.String[] { "Username", });
    internal_static_LoadUserReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_LoadUserReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LoadUserReply_descriptor,
        new java.lang.String[] { "Id", "AuthId", "Name", "Password", "Nick", "Telephone", "Email", "UserCode", "Disable", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
